upstream import {
    server importration:4201;
}

upstream basalrationapi {
    server basalrationapi:4900;
}

upstream rationapi {
    server rationapi:5156;
}

upstream energyfoodapi {
    server energyfoodapi:4300;
}

upstream normapi {
    server normapi:4850;
}

server {
    listen 8080;
    server_name localhost dev.groep5.han5.minor.infosupport.dev groep5.han5.minor.infosupport.dev;

    # Serve Angular app
    root /usr/share/nginx/html;
    index index.html;

    # Redirect Angular routes to index.html
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Serve static files with correct MIME types
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|otf|eot|ttf|otf|json)$ {
        try_files $uri =404;
        access_log off;
        expires 1M;
        add_header Cache-Control "public";
    }

    # Proxy requests to importration
    location /importration/ {
        proxy_pass http://import/;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
    }

    # Proxy requests to basalrationapi
    location /basalrationapi/ {
        proxy_pass http://basalrationapi/;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
    }

    # Proxy requests to rationapi
    location /rationapi/ {
        proxy_pass http://rationapi/;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
    }

    # Proxy requests to energyfoodapi
    location /energyfoodapi/ {
        proxy_pass http://energyfoodapi/;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
    }

    location /normapi/ {
        proxy_pass http://normapi/;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
    }

    # Error handling
    error_page 404 /index.html;
    location = /40x.html {
        root /usr/share/nginx/html;
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
