apiVersion: v1
data:
  rabbitmq.conf: |
    default_user = rantsoenwijzer
    default_pass = VWmm1uhBya5yX5L8g8vz
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: rabbitmq
  name: rabbitmq-cm1
