// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Norms.DAL;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Norms.Migrations
{
    [DbContext(typeof(NormDB))]
    [Migration("20250121000827_fixNutrientTypeCodeLength")]
    partial class fixNutrientTypeCodeLength
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Advice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CowId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CowId");

                    b.ToTable("Advice", "public");
                });

            modelBuilder.Entity("Domain.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Category", "public");
                });

            modelBuilder.Entity("Domain.Entities.Cow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Days")
                        .HasColumnType("integer");

                    b.Property<int?>("FarmId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Fat")
                        .HasColumnType("numeric");

                    b.Property<int>("LactationPeriodId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Milk")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ParityId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Protein")
                        .HasColumnType("numeric");

                    b.Property<decimal>("RV")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("FarmId");

                    b.HasIndex("LactationPeriodId");

                    b.HasIndex("ParityId");

                    b.ToTable("Cow", "public");
                });

            modelBuilder.Entity("Domain.Entities.Farm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("LivestockFeedAdvisorId")
                        .HasColumnType("integer");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LivestockFeedAdvisorId");

                    b.ToTable("Farm", "public");
                });

            modelBuilder.Entity("Domain.Entities.FeedType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<double>("DsProcent")
                        .HasColumnType("double precision");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("FeedType", "public");
                });

            modelBuilder.Entity("Domain.Entities.LactationPeriod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EndDay")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StartDay")
                        .HasColumnType("integer");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("LactationPeriods", "public");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndDay = 40,
                            Name = "ca. 0-40 dgn",
                            StartDay = 0,
                            Value = 1
                        },
                        new
                        {
                            Id = 2,
                            EndDay = 80,
                            Name = "ca. 41-80 dgn",
                            StartDay = 41,
                            Value = 2
                        },
                        new
                        {
                            Id = 3,
                            EndDay = 120,
                            Name = "ca. 81-120 dgn",
                            StartDay = 81,
                            Value = 3
                        },
                        new
                        {
                            Id = 4,
                            EndDay = 200,
                            Name = "ca. 121-200 dgn",
                            StartDay = 121,
                            Value = 4
                        },
                        new
                        {
                            Id = 5,
                            EndDay = 280,
                            Name = "ca. 201-280 dgn",
                            StartDay = 201,
                            Value = 5
                        },
                        new
                        {
                            Id = 6,
                            EndDay = 2147483647,
                            Name = "from 281 dgn",
                            StartDay = 281,
                            Value = 6
                        });
                });

            modelBuilder.Entity("Domain.Entities.LivestockFeedAdvisor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("LivestockFeedAdvisor", "public");
                });

            modelBuilder.Entity("Domain.Entities.LivestockProperties", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AvgLactationDays")
                        .HasColumnType("integer");

                    b.Property<int?>("AvgWeightCow")
                        .HasColumnType("integer");

                    b.Property<int?>("CalvingAge")
                        .HasColumnType("integer");

                    b.Property<int?>("Heiffers")
                        .HasColumnType("integer");

                    b.Property<decimal?>("MilkFat")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("MilkProtein")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Netto")
                        .HasColumnType("numeric");

                    b.Property<int?>("OldCows")
                        .HasColumnType("integer");

                    b.Property<decimal?>("ProductionLevel")
                        .HasColumnType("numeric");

                    b.Property<int?>("SecondCalves")
                        .HasColumnType("integer");

                    b.Property<int?>("TotalCows")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("LivestockProperties", "public");
                });

            modelBuilder.Entity("Domain.Entities.Norm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("LactationPeriodId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("MaxValue")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("MinValue")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("NutrientTypeId")
                        .HasColumnType("integer");

                    b.Property<int>("RationType")
                        .HasColumnType("integer");

                    b.Property<string>("Remark")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LactationPeriodId");

                    b.HasIndex("NutrientTypeId");

                    b.ToTable("Norms", "public");
                });

            modelBuilder.Entity("Domain.Entities.Nutrient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("NutrientTypeId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("NutrientTypeId");

                    b.ToTable("Nutrient", "public");
                });

            modelBuilder.Entity("Domain.Entities.NutrientType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("NutrientTypes", "public");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "Vem",
                            Value = 1
                        },
                        new
                        {
                            Id = 2,
                            Code = "Bzb",
                            Value = 2
                        },
                        new
                        {
                            Id = 3,
                            Code = "Dvp",
                            Value = 3
                        },
                        new
                        {
                            Id = 4,
                            Code = "Oep",
                            Value = 4
                        },
                        new
                        {
                            Id = 5,
                            Code = "PercentRv",
                            Value = 5
                        },
                        new
                        {
                            Id = 6,
                            Code = "VemDvp",
                            Value = 6
                        },
                        new
                        {
                            Id = 7,
                            Code = "Zw",
                            Value = 7
                        },
                        new
                        {
                            Id = 8,
                            Code = "Bw",
                            Value = 8
                        },
                        new
                        {
                            Id = 9,
                            Code = "BzbRv",
                            Value = 9
                        },
                        new
                        {
                            Id = 10,
                            Code = "Fop",
                            Value = 10
                        },
                        new
                        {
                            Id = 11,
                            Code = "Wfkh",
                            Value = 11
                        },
                        new
                        {
                            Id = 12,
                            Code = "Wfre",
                            Value = 12
                        },
                        new
                        {
                            Id = 13,
                            Code = "WfreWfkh",
                            Value = 13
                        },
                        new
                        {
                            Id = 14,
                            Code = "Sfkh",
                            Value = 14
                        },
                        new
                        {
                            Id = 15,
                            Code = "Sfre",
                            Value = 15
                        },
                        new
                        {
                            Id = 16,
                            Code = "Lacto",
                            Value = 16
                        },
                        new
                        {
                            Id = 17,
                            Code = "Re",
                            Value = 17
                        },
                        new
                        {
                            Id = 18,
                            Code = "ReInc",
                            Value = 18
                        },
                        new
                        {
                            Id = 19,
                            Code = "PercentDs",
                            Value = 19
                        },
                        new
                        {
                            Id = 20,
                            Code = "Ndf",
                            Value = 20
                        },
                        new
                        {
                            Id = 21,
                            Code = "DpMeth",
                            Value = 21
                        },
                        new
                        {
                            Id = 22,
                            Code = "DpLys",
                            Value = 22
                        },
                        new
                        {
                            Id = 23,
                            Code = "DpHis",
                            Value = 23
                        },
                        new
                        {
                            Id = 24,
                            Code = "DpLeu",
                            Value = 24
                        },
                        new
                        {
                            Id = 25,
                            Code = "Sui",
                            Value = 25
                        },
                        new
                        {
                            Id = 26,
                            Code = "Zet",
                            Value = 26
                        },
                        new
                        {
                            Id = 27,
                            Code = "Nfc",
                            Value = 27
                        },
                        new
                        {
                            Id = 28,
                            Code = "Rc",
                            Value = 28
                        },
                        new
                        {
                            Id = 29,
                            Code = "SuSaz",
                            Value = 29
                        },
                        new
                        {
                            Id = 30,
                            Code = "Bzet",
                            Value = 30
                        },
                        new
                        {
                            Id = 31,
                            Code = "Ras",
                            Value = 31
                        },
                        new
                        {
                            Id = 32,
                            Code = "Nh3",
                            Value = 32
                        },
                        new
                        {
                            Id = 33,
                            Code = "Ca",
                            Value = 33
                        },
                        new
                        {
                            Id = 34,
                            Code = "CaP",
                            Value = 34
                        },
                        new
                        {
                            Id = 35,
                            Code = "NP",
                            Value = 35
                        },
                        new
                        {
                            Id = 36,
                            Code = "P",
                            Value = 36
                        },
                        new
                        {
                            Id = 37,
                            Code = "Na",
                            Value = 37
                        },
                        new
                        {
                            Id = 38,
                            Code = "KNa",
                            Value = 38
                        },
                        new
                        {
                            Id = 39,
                            Code = "K",
                            Value = 39
                        },
                        new
                        {
                            Id = 40,
                            Code = "MgK",
                            Value = 40
                        },
                        new
                        {
                            Id = 41,
                            Code = "Mg",
                            Value = 41
                        },
                        new
                        {
                            Id = 42,
                            Code = "Cl",
                            Value = 42
                        },
                        new
                        {
                            Id = 43,
                            Code = "S",
                            Value = 43
                        },
                        new
                        {
                            Id = 44,
                            Code = "Kav",
                            Value = 44
                        },
                        new
                        {
                            Id = 45,
                            Code = "MnMg",
                            Value = 45
                        },
                        new
                        {
                            Id = 46,
                            Code = "ZnMg",
                            Value = 46
                        },
                        new
                        {
                            Id = 47,
                            Code = "FeMg",
                            Value = 47
                        },
                        new
                        {
                            Id = 48,
                            Code = "CuMg",
                            Value = 48
                        },
                        new
                        {
                            Id = 49,
                            Code = "MoMg",
                            Value = 49
                        },
                        new
                        {
                            Id = 50,
                            Code = "JoMg",
                            Value = 50
                        },
                        new
                        {
                            Id = 51,
                            Code = "CoMcg",
                            Value = 51
                        },
                        new
                        {
                            Id = 52,
                            Code = "SeMcg",
                            Value = 52
                        },
                        new
                        {
                            Id = 53,
                            Code = "AIE",
                            Value = 53
                        },
                        new
                        {
                            Id = 54,
                            Code = "D3IE",
                            Value = 54
                        },
                        new
                        {
                            Id = 55,
                            Code = "EIE",
                            Value = 55
                        },
                        new
                        {
                            Id = 56,
                            Code = "Niacine",
                            Value = 56
                        },
                        new
                        {
                            Id = 57,
                            Code = "Choline",
                            Value = 57
                        },
                        new
                        {
                            Id = 58,
                            Code = "Biotine",
                            Value = 58
                        },
                        new
                        {
                            Id = 59,
                            Code = "Rvet",
                            Value = 59
                        },
                        new
                        {
                            Id = 60,
                            Code = "Klauw",
                            Value = 60
                        },
                        new
                        {
                            Id = 61,
                            Code = "Uier",
                            Value = 61
                        },
                        new
                        {
                            Id = 62,
                            Code = "Vruchtbaarheid",
                            Value = 62
                        },
                        new
                        {
                            Id = 63,
                            Code = "KgMelk",
                            Value = 63
                        },
                        new
                        {
                            Id = 64,
                            Code = "EiwitPercent",
                            Value = 64
                        },
                        new
                        {
                            Id = 65,
                            Code = "EiwitGram",
                            Value = 65
                        },
                        new
                        {
                            Id = 66,
                            Code = "VetGram",
                            Value = 66
                        },
                        new
                        {
                            Id = 67,
                            Code = "VEGram",
                            Value = 67
                        },
                        new
                        {
                            Id = 68,
                            Code = "TotaleZuren",
                            Value = 68
                        },
                        new
                        {
                            Id = 69,
                            Code = "Ureum",
                            Value = 69
                        });
                });

            modelBuilder.Entity("Domain.Entities.Parity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ParityTypeValue")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Parity", "public");
                });

            modelBuilder.Entity("Domain.Entities.Ration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("LivestockPropertyId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("LivestockPropertyId")
                        .IsUnique();

                    b.ToTable("Ration", "public");
                });

            modelBuilder.Entity("Domain.Entities.RationFeedType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FeedTypeId")
                        .HasColumnType("integer");

                    b.Property<decimal>("GAmount")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsEnergyFeed")
                        .HasColumnType("boolean");

                    b.Property<decimal>("KgAmount")
                        .HasColumnType("numeric");

                    b.Property<int>("RationId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FeedTypeId");

                    b.HasIndex("RationId");

                    b.ToTable("RationFeedType", "public");
                });

            modelBuilder.Entity("FeedTypeNutrient", b =>
                {
                    b.Property<int>("FeedTypesId")
                        .HasColumnType("integer");

                    b.Property<int>("NutrientsId")
                        .HasColumnType("integer");

                    b.HasKey("FeedTypesId", "NutrientsId");

                    b.HasIndex("NutrientsId");

                    b.ToTable("FeedTypeNutrient", "public");
                });

            modelBuilder.Entity("Domain.Entities.Advice", b =>
                {
                    b.HasOne("Domain.Entities.Cow", "Cow")
                        .WithMany("Advices")
                        .HasForeignKey("CowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cow");
                });

            modelBuilder.Entity("Domain.Entities.Cow", b =>
                {
                    b.HasOne("Domain.Entities.Farm", "Farm")
                        .WithMany("Cows")
                        .HasForeignKey("FarmId");

                    b.HasOne("Domain.Entities.LactationPeriod", "LactationPeriod")
                        .WithMany("Cows")
                        .HasForeignKey("LactationPeriodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Parity", "Parity")
                        .WithMany("Cows")
                        .HasForeignKey("ParityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Farm");

                    b.Navigation("LactationPeriod");

                    b.Navigation("Parity");
                });

            modelBuilder.Entity("Domain.Entities.Farm", b =>
                {
                    b.HasOne("Domain.Entities.LivestockFeedAdvisor", "LivestockFeedAdvisor")
                        .WithMany("Farms")
                        .HasForeignKey("LivestockFeedAdvisorId");

                    b.Navigation("LivestockFeedAdvisor");
                });

            modelBuilder.Entity("Domain.Entities.FeedType", b =>
                {
                    b.HasOne("Domain.Entities.Category", "Category")
                        .WithMany("FeedTypes")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Domain.Entities.Norm", b =>
                {
                    b.HasOne("Domain.Entities.LactationPeriod", "LactationPeriod")
                        .WithMany()
                        .HasForeignKey("LactationPeriodId");

                    b.HasOne("Domain.Entities.NutrientType", "NutrientType")
                        .WithMany()
                        .HasForeignKey("NutrientTypeId");

                    b.Navigation("LactationPeriod");

                    b.Navigation("NutrientType");
                });

            modelBuilder.Entity("Domain.Entities.Nutrient", b =>
                {
                    b.HasOne("Domain.Entities.NutrientType", "NutrientType")
                        .WithMany()
                        .HasForeignKey("NutrientTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NutrientType");
                });

            modelBuilder.Entity("Domain.Entities.Ration", b =>
                {
                    b.HasOne("Domain.Entities.LivestockProperties", "LivestockProperties")
                        .WithOne("Ration")
                        .HasForeignKey("Domain.Entities.Ration", "LivestockPropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LivestockProperties");
                });

            modelBuilder.Entity("Domain.Entities.RationFeedType", b =>
                {
                    b.HasOne("Domain.Entities.FeedType", "FeedType")
                        .WithMany("RationFeedTypes")
                        .HasForeignKey("FeedTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Ration", "Ration")
                        .WithMany("FeedTypes")
                        .HasForeignKey("RationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FeedType");

                    b.Navigation("Ration");
                });

            modelBuilder.Entity("FeedTypeNutrient", b =>
                {
                    b.HasOne("Domain.Entities.FeedType", null)
                        .WithMany()
                        .HasForeignKey("FeedTypesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Nutrient", null)
                        .WithMany()
                        .HasForeignKey("NutrientsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Category", b =>
                {
                    b.Navigation("FeedTypes");
                });

            modelBuilder.Entity("Domain.Entities.Cow", b =>
                {
                    b.Navigation("Advices");
                });

            modelBuilder.Entity("Domain.Entities.Farm", b =>
                {
                    b.Navigation("Cows");
                });

            modelBuilder.Entity("Domain.Entities.FeedType", b =>
                {
                    b.Navigation("RationFeedTypes");
                });

            modelBuilder.Entity("Domain.Entities.LactationPeriod", b =>
                {
                    b.Navigation("Cows");
                });

            modelBuilder.Entity("Domain.Entities.LivestockFeedAdvisor", b =>
                {
                    b.Navigation("Farms");
                });

            modelBuilder.Entity("Domain.Entities.LivestockProperties", b =>
                {
                    b.Navigation("Ration")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Parity", b =>
                {
                    b.Navigation("Cows");
                });

            modelBuilder.Entity("Domain.Entities.Ration", b =>
                {
                    b.Navigation("FeedTypes");
                });
#pragma warning restore 612, 618
        }
    }
}
